services:
  cupsd:
    image: unixorn/cupsd
    volumes:
      - './volumes/printers.conf:/etc/cups/printers.conf'
      - '/var/run/dbus:/var/run/dbus'
      - /etc/hostname:/etc/hostname:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - '${CUPS_PRINTER_DEVICE:?CUPS_PRINTER_DEVICE must be set}:${CUPS_PRINTER_DEVICE:?CUPS_PRINTER_DEVICE must be set}'
    ports:
      - '631:631'
    restart: unless-stopped