version: "3.7"

services:
  officer:
    image: funkyfuture/deck-chores:1
    restart: unless-stopped
    environment:
      TIMEZONE: Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
