version: '2'
services:
  certbot:
    image: certbot/dns-cloudflare:arm32v6-latest
    volumes:
      - ./volumes/etc:/etc/letsencrypt
      - ./volumes/logs:/var/log/letsencrypt
      - ./volumes/lib:/var/lib/letsencrypt
      - ../secrets/certbot_credentials:/credentials
    command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials /credentials/cred.ini -d *.rubie-todd.uk --agree-tos --email rich.rubie@gmail.com --keep-until-expiring
