# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env_file:
      - ../../secrets/pihole/variables.env
    environment:
      TZ: 'Europe/London'
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      FTLCONF_webserver_tls_cert: /cert/pihole.pem
      FTLCONF_webserver_domain: rubie-todd.uk
      FTLCONF_dns_listeningMode: 'all'
    # Volumes store your data between container upgrades
    volumes:
       - './volumes/etc-pihole/:/etc/pihole/'
       - './volumes/etc-dnsmasq.d/:/etc/dnsmasq.d/'
       - '../../secrets/cert:/cert'
    dns:
      - 1.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped