version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant
    ports:
      - "2053:2053/tcp"
    volumes:
      - ./volumes/config:/config
    restart: always
    network_mode: host
