services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    labels:
      - "com.github.richr.cert-reload=true"
    volumes:
      - ./volumes/config:/config
      - ../secrets/cert:/config/ssl:ro
      - ../secrets/homeAssistant/google-assistant.json:/config/google-assistant.json:ro
      - ../secrets/homeAssistant/googlecloud.json:/config/googlecloud.json:ro
      - ../secrets/homeAssistant/secrets.yaml:/config/secrets.yaml:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host