services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    labels:
      - "com.github.richr.cert-reload=true"
    # ports:
    #   - "2053:2053/tcp"
    volumes:
      - ./volumes/config:/config
      - ../secrets/cert:/config/ssl
      - ../secrets/homeAssistant/google-assistant.json:/config/google-assistant.json
      - ../secrets/homeAssistant/googlecloud.json:/config/googlecloud.json
      - ../secrets/homeAssistant/secrets.yaml:/config/secrets.yaml
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host