version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant
    ports:
      - "2053:2053/tcp"
    volumes:
      - ./volumes/config:/config
      - ../secrets/cert:/config/ssl
      - ../secrets/homeAssistant/google-assistant.json:/config/google-assistant.json
      - ../secrets/homeAssistant/secrets.yaml:/config/secrets.yaml
    restart: always
    network_mode: host
  volumerise:
    container_name: homeAssistantVolmerise
    image: blacklabelops/volumerize
    volumes:
      - ./volumes/volumerize_cache:/volumerize-cache
      - ../secrets/volumerize_credentials:/credentials
      - ./volumes/config:/source:ro
    environment:
      VOLUMERIZE_SOURCE: '/source'
      VOLUMERIZE_TARGET: 'gdocs://rich.rubie@gmail.com/backup/homeAssistant'
      VOLUMERIZE_FULL_IF_OLDER_THAN: '7D'