FROM pihole/pihole:latest

LABEL image="redfox/pi-holeWithCloudFlared:debian_amd64"

RUN mkdir argo-tunnel
RUN wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.tgz
RUN tar -xvzf cloudflared-stable-linux-amd64.tgz -C ./argo-tunnel
RUN rm cloudflared-stable-linux-amd64.tgz

CMD ["/bin/sh", "-c", "/argo-tunnel/cloudflared proxy-dns --address 0.0.0.0 --port 54 --upstream https://1.1.1.1/.well-known/dns-query --upstream https://1.0.0.1/.well-known/dns-query"]
