version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=123
      - ZONE=redfoxfactory.co.uk
      - SUBDOMAIN=home
      - PROXIED=true