version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    env_file:
      - ../secrets/cloudflare_ddns/variables.env
    environment:
      - ZONE=rubie-todd.uk
      - SUBDOMAIN=home
      - PROXIED=false