FROM pihole/pihole:latest

LABEL image="richrubie/pihole:latest"

RUN mkdir argo-tunnel
RUN wget -O cloudflared.tgz https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.tgz
RUN tar -xvzf cloudflared.tgz -C ./argo-tunnel
RUN rm cloudflared.tgz

CMD ["/bin/sh", "-c", "/argo-tunnel/cloudflared proxy-dns --address 0.0.0.0 --port 54 --upstream https://1.1.1.1/.well-known/dns-query --upstream https://1.0.0.1/.well-known/dns-query"]
