- id: '1599811624657'
  alias: Attic - Light on in morning
  description: ''
  trigger:
  - at: '8:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - brightness_pct: 100
    device_id: bc598afac29144f580920916f42065b5
    domain: light
    entity_id: light.shelly_shdm_2_e0980695b40b
    type: turn_on
  mode: single
- id: '1600867231219'
  alias: Back Bedroom - Lights off  in the morning
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id: 0dd7d3bda1b345958f4409c9cb3c3318
  mode: single
- id: '1600867375526'
  alias: Back Bedroom - Lights on in evening
  description: ''
  trigger:
  - at: '18:00'
    platform: time
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 50
    target:
      area_id: 0dd7d3bda1b345958f4409c9cb3c3318
  mode: single
- id: '1609969268420'
  alias: Master bedroom - Wall lights on in evening
  description: ''
  trigger:
  - platform: time
    at: '18:00'
  condition: []
  action:
  - service: light.turn_on
    target:
      device_id:
      - 5b37f965dd914df99ffa9e725c576fd3
      - 4c9beab5f0cc42ddacf2988ab9bc8e90
  mode: single
- id: '1613940955727'
  alias: Landing - Light on dim in evening
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 10
      transition: 300
    entity_id: light.shelly_shdm_1_f3a619
  mode: single
- id: '1613941020607'
  alias: Landing - Lights on full in morning
  description: ''
  trigger:
  - platform: time
    at: 08:00
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      transition: 300
    target:
      entity_id: light.shelly_shdm_1_f3a619
  mode: single
- id: '1632834080174'
  alias: Attic - Send Notification - Raining and windows are open
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.pudsey_probability_of_precipitation_3_hourly
    attribute: attribution
    from: '50'
    to: '100'
  condition:
  - condition: or
    conditions:
    - type: is_open
      condition: device
      device_id: 1f5a025605e6f23fa0ce984ca6df6114
      entity_id: binary_sensor.0x00158d0003cf3b89_contact
      domain: binary_sensor
    - type: is_open
      condition: device
      device_id: 17bb7d3c08dcff6a63cc1f3dbe5255d3
      entity_id: binary_sensor.aqara_dw_2_contact
      domain: binary_sensor
  action:
  - device_id: d840b2d682f64d2895b9f4faff8af720
    domain: mobile_app
    type: notify
    title: I'ts going to rain
    message: Attic windows are open
  mode: single
- id: '1636967707722'
  alias: Landing - Lights brighter in the morning
  description: ''
  trigger:
  - platform: time
    at: 07:20
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 300
      brightness_pct: 25
    target:
      entity_id: light.shelly_shdm_1_f3a619
  mode: single
- id: '1640619543027'
  alias: Toilet - Light auto on off
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.toilet
    id: timer_finished
  - type: motion
    platform: device
    device_id: fb70afcf862ef62a6c6580eae94a1da9
    entity_id: binary_sensor.aqara_pir_3_occupancy
    domain: binary_sensor
    id: motion_detected
  - platform: state
    entity_id:
    - binary_sensor.aqara_dw_3_toilet_door_contact
    to: 'on'
    id: door_open
  - platform: state
    entity_id: light.shelly_shdm_2_e8db84d787f2
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: timer_finished
      sequence:
      - service: light.turn_off
        target:
          area_id: toilet
        data: {}
    default:
    - service: light.turn_on
      target:
        area_id: toilet
      data: {}
    - service: timer.start
      data:
        duration: '0'
      target:
        area_id: toilet
  - condition: trigger
    id: motion_detected
  - condition: state
    entity_id: binary_sensor.aqara_dw_3_toilet_door_contact
    state: 'off'
  - service: timer.pause
    target:
      area_id: toilet
    data: {}
  mode: queued
  max: 10
- id: '1641238468956'
  alias: Cellar  - Motion-activated Light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_sensor_1_occupancy
      light_target:
        area_id: 9fa5ef4d3cf2d9322333bca777b2edea
      no_motion_wait: 300
- id: '1641915079598'
  alias: Bathroom  - Light on
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: ef2bf7a7bb707319e79c8a8b502267c8
    entity_id: binary_sensor.aqara_pir_2_occupancy
    domain: binary_sensor
    id: motion_detected
  - platform: state
    entity_id:
    - binary_sensor.aqara_dw_4_bathroom_door_contact
    to: 'on'
    id: door_open
  - type: turned_on
    platform: device
    device_id: 0a0a33ace30a18735189d4e79484f5e8
    entity_id: binary_sensor.shelly_shdm_2_3c6105e58aa9_1_switch
    domain: binary_sensor
    id: Light on
  condition:
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.aqara_pir_2_illuminance
      below: '50'
  action:
  - service: light.turn_on
    target:
      area_id: bathroom
    data: {}
  - service: timer.start
    data:
      duration: '0'
    target:
      area_id: bathroom
  - condition: trigger
    id: motion_detected
  - condition: state
    state: 'off'
    entity_id: binary_sensor.aqara_dw_4_bathroom_door_contact
  - service: timer.pause
    target:
      area_id: bathroom
    data: {}
  mode: queued
  max: 10
- id: '1643551976381'
  alias: Bathroom - Set brightness
  description: ''
  trigger:
  - platform: time
    at: 00:30
    id: Night
  - platform: time
    at: 07:00
    id: Morning
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: Night
      sequence:
      - service: input_number.set_value
        target:
          area_id: bathroom
        data:
          value: 30
    - conditions:
      - condition: trigger
        id: Morning
      sequence:
      - service: input_number.set_value
        target:
          area_id: bathroom
        data:
          value: 100
    default: []
  mode: single
- id: '1643553622757'
  alias: Bathroom - Light off
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id: bathroom
    data:
      transition: 30
  mode: single
