- id: '1599811624657'
  alias: Turn on office lights
  description: ''
  trigger:
  - at: '8:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - brightness_pct: 100
    device_id: bc598afac29144f580920916f42065b5
    domain: light
    entity_id: light.shelly_shdm_2_e0980695b40b
    type: turn_on
  mode: single
- id: '1600867231219'
  alias: Turn Off Ollie lights at 8.30am
  description: ''
  trigger:
  - at: '8:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - wed
    - thu
    - fri
  action:
  - device_id: 12a5db9394464e5faae1e777a36e0463
    domain: light
    entity_id: light.shelly_shdm_1_f3a4d4
    type: turn_off
  - type: turn_off
    device_id: 01e059b1c24a4d3c9cff357c828aa6e9
    entity_id: switch.starlight
    domain: switch
  - type: turn_off
    device_id: 763f3b38eba2b821afcbd1f1537ea25f
    entity_id: light.shelly_shsw_1_483fda9421d1
    domain: light
  mode: single
- id: '1600867375526'
  alias: Turn on Ollie lights at 18:00
  description: ''
  trigger:
  - at: '18:00'
    platform: time
  condition: []
  action:
  - brightness_pct: 50
    device_id: 12a5db9394464e5faae1e777a36e0463
    domain: light
    entity_id: light.shelly_shdm_1_f3a4d4
    type: turn_on
  - type: turn_on
    device_id: 01e059b1c24a4d3c9cff357c828aa6e9
    entity_id: switch.starlight
    domain: switch
  - type: turn_on
    device_id: 763f3b38eba2b821afcbd1f1537ea25f
    entity_id: light.shelly_shsw_1_483fda9421d1
    domain: light
  mode: single
- id: '1604354516744'
  alias: Tell Ollie it's bath time
  description: ''
  trigger:
  - platform: time
    at: '18:30'
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      message: Ollie, are you listening? Its shower time, please go to the bathroom
        and get undressed.
      entity_id: media_player.attic_display
      language: en-uk
  mode: single
- id: '1609164746747'
  alias: Turn Off Ollie main light at bed time
  description: ''
  trigger:
  - at: '19:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - device_id: 12a5db9394464e5faae1e777a36e0463
    domain: light
    entity_id: light.shelly_shdm_1_f3a4d4
    type: turn_off
  mode: single
- id: '1609164821532'
  alias: Turn Off Ollie lamp at bedtime
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - type: turn_off
    device_id: 763f3b38eba2b821afcbd1f1537ea25f
    entity_id: light.shelly_shsw_1_483fda9421d1
    domain: light
  mode: single
- id: '1609164909290'
  alias: Turn Off Ollie starlights at bedtime
  description: ''
  trigger:
  - platform: time
    at: '20:45'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - type: turn_off
    device_id: 01e059b1c24a4d3c9cff357c828aa6e9
    entity_id: switch.starlight
    domain: switch
  mode: single
- id: '1609969268420'
  alias: turn on masterbedroom lights at 7pm
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition: []
  action:
  - domain: light
    entity_id: light.shelly_shdm_2_e09806954c45
    device_id: 5b37f965dd914df99ffa9e725c576fd3
    type: turn_on
  - domain: light
    entity_id: light.shelly_shdm_2_e0980695b38b
    device_id: 4c9beab5f0cc42ddacf2988ab9bc8e90
    type: turn_on
  mode: single
- id: '1613940955727'
  alias: Set landing light to 10% at 7pm
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 10
      transition: 300
    entity_id: light.shelly_shdm_1_f3a619
  mode: single
- id: '1613941020607'
  alias: Set landing light to 100% in the Morning
  description: ''
  trigger:
  - platform: time
    at: 08:00
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      transition: 300
    target:
      entity_id: light.shelly_shdm_1_f3a619
  mode: single
- id: '1632403358752'
  alias: Toilet - Motion for light
  description: 'Toilet '
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 307
      light_target:
        area_id: toilet
      motion_entity: binary_sensor.aqara_pir_3_occupancy
- id: '1632834080174'
  alias: Raining and Attic windows are open notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.pudsey_probability_of_precipitation_3_hourly
    attribute: attribution
    from: '50'
    to: '100'
  condition:
  - condition: or
    conditions:
    - type: is_open
      condition: device
      device_id: 1f5a025605e6f23fa0ce984ca6df6114
      entity_id: binary_sensor.0x00158d0003cf3b89_contact
      domain: binary_sensor
    - type: is_open
      condition: device
      device_id: 17bb7d3c08dcff6a63cc1f3dbe5255d3
      entity_id: binary_sensor.aqara_dw_2_contact
      domain: binary_sensor
  action:
  - device_id: d840b2d682f64d2895b9f4faff8af720
    domain: mobile_app
    type: notify
    title: I'ts going to rain
    message: Attic windows are open
  mode: single
- id: '1636967707722'
  alias: Set landing light to 50% in the Morning
  description: ''
  trigger:
  - platform: time
    at: 07:20
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 300
      brightness_pct: 25
    target:
      entity_id: light.shelly_shdm_1_f3a619
  mode: single
- id: '1640619543027'
  alias: Toilet light auto on off
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.toilet
    id: timer_finished
  - type: motion
    platform: device
    device_id: fb70afcf862ef62a6c6580eae94a1da9
    entity_id: binary_sensor.aqara_pir_3_occupancy
    domain: binary_sensor
    id: motion_detected
  - platform: state
    entity_id: binary_sensor.aqara_dw_3_contact
    to: 'on'
    id: door_open
  - platform: state
    entity_id: light.shelly_shdm_2_e8db84d787f2
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: timer_finished
      sequence:
      - service: light.turn_off
        target:
          area_id: toilet
        data: {}
    default:
    - service: light.turn_on
      target:
        area_id: toilet
    - service: timer.start
      data:
        duration: '0'
      target:
        area_id: toilet
  - condition: trigger
    id: motion_detected
  - condition: state
    entity_id: binary_sensor.aqara_dw_3_contact
    state: 'off'
  - service: timer.pause
    target:
      area_id: toilet
  mode: queued
  max: 10
- id: '1641238468956'
  alias: Cellar Motion-activated Light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_sensor_1_occupancy
      light_target:
        area_id: 9fa5ef4d3cf2d9322333bca777b2edea
      no_motion_wait: 300
- id: '1641915079598'
  alias: Bathroom light auto on off
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom
    id: timer_finished
  - type: motion
    platform: device
    device_id: ef2bf7a7bb707319e79c8a8b502267c8
    entity_id: binary_sensor.aqara_pir_2_occupancy
    domain: binary_sensor
    id: motion_detected
  - platform: state
    entity_id: binary_sensor.aqara_dw_4_contact
    to: 'on'
    id: door_open
  - platform: state
    to: 'on'
    entity_id: light.shelly_shdm_2_3c6105e58aa9
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: timer_finished
      sequence:
      - service: light.turn_off
        data: {}
        target:
          area_id: bathroom
    default:
    - service: light.turn_on
      target:
        area_id: bathroom
    - service: timer.start
      data:
        duration: '0'
      target:
        area_id: bathroom
  - condition: trigger
    id: motion_detected
  - condition: state
    state: 'off'
    entity_id: binary_sensor.aqara_dw_4_contact
  - service: timer.pause
    target:
      area_id: bathroom
  mode: queued
  max: 10
