homeassistant:
  internal_url: https://pi2.redfoxfactory.co.uk:2053

http:
 server_port: 2053
 ssl_certificate: ssl/fullchain.pem
 ssl_key: ssl/privkey.pem

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: en-uk
    # base_url: https://pi1.redfoxfactory.co.uk:2053

google_assistant:
  report_state: true
  project_id: home-automation-337120
  service_account: !include google-assistant.json

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  discovery: true
  broker: pi2.redfoxfactory.co.uk
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id

