- id: '1728162135232'
  name: Eating dinner
  entities:
    light.shelly_shdm_2_e0980695b097:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 127
      shelly_type: Shelly Dimmer 2
      shelly_id: E0980695B097
      ip_address: 192.168.1.43
      room: Dining room
      protocols:
      - CoAP-discovery
      - CoAP-msg
      - poll
      over_temp: 0
      has_firmware_update: false
      switch_1: false
      switch_2: false
      friendly_name: Dining room - Ceiling Light
      supported_features: 1
      state: 'on'
    light.shelly_shdm_2_a4e57cba3592:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 64
      shelly_type: Shelly Dimmer 2
      shelly_id: A4E57CBA3592
      ip_address: 192.168.1.184
      room: Dining room
      protocols:
      - CoAP-discovery
      - CoAP-msg
      - poll
      over_temp: 0
      has_firmware_update: true
      switch_1: false
      switch_2: false
      friendly_name: Dining room - Ceiling spot lights
      supported_features: 1
      state: 'on'
  icon: mdi:globe-light-outline
  metadata:
    light.shelly_shdm_2_e0980695b097:
      entity_only: true
    light.shelly_shdm_2_a4e57cba3592:
      entity_only: true
