- id: '1595973678649'
  name: master bedroom bed time
  entities:
    light.shelly_shdm_1_db34d3:
      brightness: 61
      friendly_name: Master - Main light
      has_firmware_update: false
      ip_address: 192.168.1.12
      over_temp: false
      protocols:
      - CoAP-discovery
      - CoAP-msg
      - poll
      - mDns
      room: Master
      shelly_id: DB34D3
      shelly_type: Shelly Dimmer
      state: 'on'
      supported_features: 1
      switch_1: false
      switch_2: false
    light.shelly_shdm_2_e09806954c45:
      brightness: 68
      friendly_name: Master - Rich
      has_firmware_update: false
      ip_address: 192.168.1.72
      over_temp: false
      protocols:
      - CoAP-discovery
      - CoAP-msg
      - poll
      - mDns
      room: Master
      shelly_id: E09806954C45
      shelly_type: Shelly Dimmer 2
      state: 'on'
      supported_features: 1
      switch_1: true
      switch_2: false
    sensor.shelly_shdm_1_db34d3_current_consumption:
      friendly_name: Master - Main light
      icon: mdi:flash-outline
      ip_address: 192.168.1.12
      room: Master
      shelly_id: DB34D3
      shelly_type: Shelly Dimmer
      state: '3'
      unit_of_measurement: W
    sensor.shelly_shdm_1_db34d3_total_consumption:
      device_class: power
      friendly_name: Master - Main light - Total consumption
      icon: mdi:flash-circle
      ip_address: 192.168.1.12
      room: Master
      shelly_id: DB34D3
      shelly_type: Shelly Dimmer
      state: '0.33'
      unit_of_measurement: kWh
- id: '1595973740088'
  name: master off
  entities:
    light.shelly_shdm_1_db34d3:
      friendly_name: Master - Main light
      has_firmware_update: false
      ip_address: 192.168.1.12
      over_temp: false
      protocols:
      - CoAP-discovery
      - CoAP-msg
      - poll
      - mDns
      room: Master
      shelly_id: DB34D3
      shelly_type: Shelly Dimmer
      state: 'off'
      supported_features: 1
      switch_1: false
      switch_2: false
    light.shelly_shdm_2_e09806954c45:
      friendly_name: Master - Rich
      has_firmware_update: false
      ip_address: 192.168.1.72
      over_temp: false
      protocols:
      - CoAP-discovery
      - CoAP-msg
      - poll
      - mDns
      room: Master
      shelly_id: E09806954C45
      shelly_type: Shelly Dimmer 2
      state: 'off'
      supported_features: 1
      switch_1: true
      switch_2: false
