- id: '1641239820262'
  name: Ollie bed time
  entities:
    switch.starlight:
      friendly_name: Starlight
      state: 'on'
    switch.starlights_led:
      icon: mdi:led-on
      friendly_name: Starlights LED
      state: 'on'
    switch.shelly_shsw_1_483fda9421d1:
      restored: true
      friendly_name: Shelly 1 - 483FDA9421D1
      supported_features: 0
      state: unavailable
    light.shelly_shsw_1_483fda9421d1:
      supported_color_modes:
      - onoff
      color_mode: onoff
      shelly_type: Shelly 1
      shelly_id: 483FDA9421D1
      ip_address: 192.168.1.102
      room: Ollie
      protocols:
      - CoAP-msg
      - poll
      has_firmware_update: false
      switch: false
      friendly_name: Ollie - Lamp
      supported_features: 0
      state: 'on'
    light.shelly_shdm_1_f3a4d4:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 73
      shelly_type: Shelly Dimmer
      shelly_id: F3A4D4
      ip_address: 192.168.1.11
      room: Ollie
      protocols:
      - mDns
      - CoAP-msg
      - poll
      over_temp: 0
      has_firmware_update: false
      switch_1: true
      switch_2: false
      friendly_name: Ollie - Light
      supported_features: 1
      state: 'on'
