version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./volumes/data:/data
      - ../secrets/cert:/data/cert

    user: "root:root"

volumes:
  node-red-data:

networks:
  node-red-net: