homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
frontend:
  enabled: true
  port: 8081
advanced:
  log_level: debug
  last_seen: 'ISO_8601_local'
blocklist:
  - '0x847127fffe329086'
  - '0x0c4314fffef7874a'
devices:
  '0x00158d000588ea32':
    friendly_name: Aqara HT 2 - Back Bedroom
  '0x00158d0005889532':
    friendly_name: Aqara HT 4 - Living Room
  '0x00158d00054d43fa':
    friendly_name: Aqara PIR 1 - Cellar
  '0x00158d00068b38c9':
    friendly_name: Aqara HT 7 - Bathroom
  '0x00158d0006c032d8':
    friendly_name: Aqara PIR 3 - Toilet
  '0x00158d0003cf3b89':
    friendly_name: Aqara DW 1 - Attic Window Front
  '0x00158d0002ec53d4':
    friendly_name: Aqara DW 2 - Attic Window Back
  '0x00158d0003ceb910':
    friendly_name: Aqara DW 4 - Bathroom Door
  '0x2c1165fffea1800f':
    friendly_name: IKEA Switch 2
  '0x00158d000588e9f4':
    friendly_name: Aqara HT 3 - Office
  '0x00158d00025d69e9':
    friendly_name: Aqara DW 3 - Toilet Door
  '0x00158d00058a650b':
    friendly_name: Aqara HT 6 - Attic
  '0x00158d0005bd8d7f':
    friendly_name: Aqara HT 1 - Front Bedroom
  '0x00158d000678e1b6':
    friendly_name: Aqara HT 8 - Toilet
  '0x00158d00054d4578':
    friendly_name: Aqara PIR 2 - Bathroom
  '0x000b57fffeba5e11':
    friendly_name: IKEA TRADFRI driver - Kitchen Cabinet Right
  '0x000d6ffffe0d2189':
    friendly_name: IKEA TRADFRI remote - Living room
  '0x385b44fffe539ef2':
    friendly_name: IKEA TRADFRI driver - Kitchen Cabinet Left
  '0x00158d0006d46d4c':
    friendly_name: Aqara PIR 4 - Cellar
  '0x00158d008afda43c':
    friendly_name: Aqara HT 5 - Dining Room
  '0x00158d008afda923':
    friendly_name: Aqara HT 9 - Cellar
  '0x00158d000af21b74':
    friendly_name: Aqara HT 10 - Kitchen
  '0x8c8b48fffe7b1f5d':
    friendly_name: IKEA Switch 4
  '0x94a081fffe5f6ac4':
    friendly_name: IKEA Switch 5
  '0x94a081fffe540ebc':
    friendly_name: IKEA Switch 6
  '0xc4d8c8fffe2e83b1':
    friendly_name: IKEA Remote 1
  '0xc4d8c8fffe2e3c6e':
    friendly_name: IKEA Remote 2
  '0x040d84fffe987564':
    friendly_name: IKEA Styrbar remote - Dining room
  '0xa4c1380e4fcfba5c':
    friendly_name: '0xa4c1380e4fcfba5c'
groups:
  '1':
    friendly_name: Kitchen cabinet lights
availability:
  enabled: true
version: 5
