homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8081
advanced:
  log_level: info
blocklist: []
devices:
  '0x00158d000588ea32':
    friendly_name: Aqara HT 2 - Back Bedroom
  '0x00158d0005889532':
    friendly_name: Aqara HT 4 - Living Room
  '0x00158d00058a6242':
    friendly_name: Aqara HT 5 - Dining Room
  '0x00158d00054d43fa':
    friendly_name: Aqara PIR 1 - Cellar
  '0x00158d00068b38c9':
    friendly_name: Aqara HT 7 - Bathroom
  '0x00158d0006c032d8':
    friendly_name: Aqara PIR 3 - Toilet
  '0x00158d0003cf3b89':
    friendly_name: Aqara DW 1 - Attic Window Front
  '0x00158d0002ec53d4':
    friendly_name: Aqara DW 2 - Attic Window Back
  '0x00158d0003ceb910':
    friendly_name: Aqara DW 4 - Bathroom Door
  '0x2c1165fffea1800f':
    friendly_name: IKEA Switch 2 - Dining Room
  '0x00158d000588e9f4':
    friendly_name: Aqara HT 3 - Office
  '0x00158d00025d69e9':
    friendly_name: Aqara DW 3 - Toilet Door
  '0x00158d00058a650b':
    friendly_name: Aqara HT 6 - Attic
  '0x00158d0005bd8d7f':
    friendly_name: Aqara HT 1 - Front Bedroom
  '0x847127fffe329086':
    friendly_name: IKEA Switch 1 - Landing
  '0x0c4314fffef7874a':
    friendly_name: IKEA Switch 3 - Office
  '0x00158d000678e1b6':
    friendly_name: Aqara HT 8 - Toilet
  '0x00158d00054d4578':
    friendly_name: Aqara PIR 2 - Bathroom
  '0x000b57fffeba5e11':
    friendly_name: IKEA TRADFRI driver - Kitchen Cabinet Right
  '0x000d6ffffe0d2189':
    friendly_name: IKEA TRADFRI remote - Kitchen
  '0x385b44fffe539ef2':
    friendly_name: IKEA TRADFRI driver - Kitchen Cabinet Left
  '0x00158d0006d46d4c':
    friendly_name: Aqara PIR 4 - Cellar
  '0x00178801082599c5':
    friendly_name: '0x00178801082599c5'
groups:
  '1':
    friendly_name: Kitchen cabinet lights
    devices:
      - 0x385b44fffe539ef2/1
      - 0x000b57fffeba5e11/1
