homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d0005bd8d7f':
    friendly_name: Aqara HT 1
  '0x00158d000588ea32':
    friendly_name: Aqara HT 2
  '0x00158d000588e9f4':
    friendly_name: Aqara HT 3
  '0x00158d0005889532':
    friendly_name: Aqara HT 4
  '0x00158d00058a6242':
    friendly_name: Aqara HT 5
  '0x00158d00058a650b':
    friendly_name: Aqara HT 6
  '0x00158d00054d43fa':
    friendly_name: Aqara PIR 1
  '0x00158d00054d4578':
    friendly_name: Aqara PIR 2
  '0x847127fffe329086':
    friendly_name: 'Ikea Switch 1'
