version: '2.2'
services:
  controller:
    image: "jacobalberty/unifi:arm32v7"
    container_name: unifi
    init: true
    restart: always
    volumes:
      - ./volumes/data:/unifi/data
      - ./volumes/log:/unifi/log
      - ./volumes/cert:/unifi/cert
      - ./volumes/init:/unifi/init.d
    environment:
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    container_name: unifi_logs
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*.log'
    restart: always
    volumes:
      - ./volumes/log:/unifi/log
