version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    # deploy:
    #   resources:
    #   limits:
    #     memory: 125M
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquittoConfig/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./volumes/mosquittoData:/mosquitto/data
      - ./volumes/mosquittoLog:/mosquitto/log
  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt
    volumes:
      - ./volumes/zigbee2mqttData:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/London