services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/mosquittoConfig/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ../secrets/mosquitto/passwd:/mosquitto/config/passwd:ro
      - ./volumes/mosquittoData:/mosquitto/data
      - ./volumes/mosquittoLog:/mosquitto/log
  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt
    volumes:
      - ./volumes/zigbee2mqttData:/app/data
      - ../secrets/zigbee2mqtt/secrets.yaml:/app/data/secret.yaml
      - ../secrets/cert:/config/ssl
      - /run/udev:/run/udev:ro
    devices:
      - ${ZIGBEE_ADAPTER:?ZIGBEE_ADAPTER must be set in .env}:/dev/ttyUSB0
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/London